pages:
  script:
    - mkdir public
    - cp index.html index.md public/
    - cp -R pdfs singularity_theory_seminar_2023 frobenius_manifold_seminar_2025 public/
  artifacts:
    paths:
      - public
  only:
    - main
